---
title: Code For Baltimore
timezone: UTC
markdown: kramdown
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@codeforbaltimore.org
description: 'Part of the Code for America Brigade network, we are a volunteer group
  of developers, designers, data geeks, and citizen activists who use creative technology
  to solve civic and social problems.'
baseurl: ''
url: http://codeforbaltimore.org
hackpad_url: http://codeforbaltimore.org
twitter_url: https://twitter.com/@codeforbmore
github_url: https://github.com/CodeForBaltimore
meetup_url: https://www.meetup.com/Code-for-Baltimore/
blog_url: http://codeforbaltimore.org
events_url: http://codeforbaltimore.org
slack_url: https://join.slack.com/t/codeforbaltimoreteam/shared_invite/enQtMzYxNzgzNDIyOTQ4LWZkZjU5YzlmODVjYmEyYTliNmFkMGViYWQ1Y2IyMDZjY2FmMjBhMzk1NmY1ZjAyMjBjOTk4ZDcyZjQ0ZjhjZTU
reveal_path: /reveal.js/
reveal_theme_path: /reveal.js/css/theme/
reveal_theme: sky.css
ga_id: INSERT_GA_ID
